import RPi.GPIO as GPIO
import time, sys, os
import pump_and_solenoid

# This expression below is correct to calculate the measure of water according the pulses generated?
# flow = count / (60 * 7.5)
# In this expression , 450 pulses generated by the sensor corresponds to 1 liter of water.
# GPIO16 - PIN36 for FLOW_METTER Data(IN)

FLOW_SENSOR = 26
global count
count = 0
global flow
flow = 0

GPIO.setmode(GPIO.BCM)

def setup():
    # GPIO.setmode(GPIO.BCM)
    GPIO.setup(FLOW_SENSOR, GPIO.IN, pull_up_down = GPIO.PUD_UP)
    pump_and_solenoid.setup()
    


def countPulse(channel):
    global count
    global flow
    count = count+1
    print(count)
    flow = count / (60 * 7.5)
    print(flow)

def start_flow_counter():
    GPIO.add_event_detect(FLOW_SENSOR, GPIO.FALLING, callback=countPulse)
    while True:
        try:
            time.sleep(1)
        except KeyboardInterrupt:
            print('\ncaught keyboard interrupt!, bye')
            GPIO.cleanup()
            count = 0
            flow = 0
            sys.exit()
            
def start_flow_counter2():
    try:
        GPIO.add_event_detect(FLOW_SENSOR, GPIO.FALLING, callback=countPulse)
        pump_and_solenoid.switch_on_sole_pump()
    except KeyboardInterrupt:
        print('\ncaught keyboard interrupt!, bye')
        GPIO.cleanup()
        count = 0
        flow = 0
        sys.exit()
        
def getCountAndFlow():
    global count
    global flow
    #count = 0
    #flow = 0
    # sys.exit()
    return (count, flow)

    
def stop_flow_counter():
    pump_and_solenoid.switch_off_sole_pump()
    GPIO.cleanup (FLOW_SENSOR)
    GPIO.setup(FLOW_SENSOR, GPIO.IN, pull_up_down = GPIO.PUD_UP)

if __name__ == "__main__":
    setup()
    stop_flow_counter()