import RPi.GPIO as GPIO
import time, sys

# This expression below is correct to calculate the measure of water according the pulses generated?
# flow = count / (60 * 7.5)
# In this expression , 450 pulses generated by the sensor corresponds to 1 liter of water.
# GPIO16 - PIN36 for FLOW_METTER Data(IN)
FLOW_SENSOR = 16

GPIO.setmode(GPIO.BCM)
GPIO.setup(FLOW_SENSOR, GPIO.IN, pull_up_down = GPIO.PUD_UP)

global count
count = 0
global flow
flow = 0

def countPulse(channel):
    global count
    count = count+1
    print(count)
    flow = count / (60 * 7.5)
    print(flow)

def start_flow_counter():
    GPIO.add_event_detect(FLOW_SENSOR, GPIO.FALLING, callback=countPulse)
    while True:
        try:
            time.sleep(1)
        except KeyboardInterrupt:
            print('\ncaught keyboard interrupt!, bye')
            GPIO.cleanup()
            count = 0
            flow = 0
            sys.exit()

def stop_flow_counter():
    GPIO.cleanup(16)
    count = 0
    flow = 0
    # sys.exit()
    return (count, flow)
